
sensor:
  - platform: mqtt
    state_topic: "home/ble_relay/A4:C1:38:B1:3C:86"
    name: "uf_kitchen_temperature"
    value_template: "{{ (-4096+(value[13:16]|int(base=16)))/10 if value[12] == 'F' else value[12:16]|int(base=16)/10 }}"
    device_class: temperature
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/ble_relay/A4:C1:38:B1:3C:86"
    name: "uf_kitchen_humidity"
    value_template: "{{ value[16:18]|int(base=16) }}"
    device_class: humidity
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/ble_relay/A4:C1:38:B1:3C:86"
    name: "uf_kitchen_battery"
    value_template: "{{ value[18:20]|int(base=16) }}"
    device_class: battery
    unit_of_measurement: "%"